.TH "Junction" 3 "Mon Jun 10 2019" "Version 2.0" "AR Sandbox for OSU Civil Construction Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Junction \- \fBJunction\fP class represents road network intersection\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearData\fP ()"
.br
.RI "Clear all current simulation data\&. "
.ti -1c
.RI "void \fBBuildJunction\fP (\fBIntersection\fP inter, bool flat)"
.br
.RI "Build an \fBIntersection\fP\&. "
.ti -1c
.RI "void \fBBuild\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Shader \fBRoad_Shader\fP"
.br
.ti -1c
.RI "List< \fBIntersection\fP > \fBJunction_List\fP"
.br
.ti -1c
.RI "bool \fBBuilt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBJunction\fP class represents road network intersection\&. 


.SH "Member Function Documentation"
.PP 
.SS "void Junction\&.BuildJunction (\fBIntersection\fP inter, bool flat)"

.PP
Build an \fBIntersection\fP\&. 
.SS "void Junction\&.ClearData ()"

.PP
Clear all current simulation data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AR Sandbox for OSU Civil Construction Engineering from the source code\&.
