.TH "MarkerManager" 3 "Mon Jun 10 2019" "Version 2.0" "AR Sandbox for OSU Civil Construction Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MarkerManager \- Provides global management and functionality for markers\&. There should only be one \fBMarkerManager\fP in the scene\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBrotateCamera\fP"
.br
.ti -1c
.RI "Transform \fBmainCameraTransform\fP"
.br
.ti -1c
.RI "float \fBARCameraHeight\fP = 4350f"
.br
.ti -1c
.RI "Text \fBuiText\fP"
.br
.ti -1c
.RI "List< \fBMarkerAction\fP > \fBmarkerActionScripts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides global management and functionality for markers\&. There should only be one \fBMarkerManager\fP in the scene\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for AR Sandbox for OSU Civil Construction Engineering from the source code\&.
