.TH "MarkerChangeIntersection" 3 "Mon Jun 10 2019" "Version 2.0" "AR Sandbox for OSU Civil Construction Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MarkerChangeIntersection
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetTrafficLightIntersection\fP (int junctionIndex)"
.br
.ti -1c
.RI "void \fBSetStopSignIntersection\fP (int junctionIndex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBtrafficLightMaterial\fP"
.br
.ti -1c
.RI "Material \fBstopSignMaterial\fP"
.br
.ti -1c
.RI "GameObject \fBjunctionsParentObject\fP"
.br
.ti -1c
.RI "\fBTraciController\fP \fBtraciController\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AR Sandbox for OSU Civil Construction Engineering from the source code\&.
