.TH "Structure" 3 "Mon Jun 10 2019" "Version 2.0" "AR Sandbox for OSU Civil Construction Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Structure \- \fBStructure\fP class stores and builds all simulation network buildings and Points of Interest\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearData\fP ()"
.br
.RI "Clear all current simulation polygon data\&. "
.ti -1c
.RI "void \fBBuild\fP ()"
.br
.RI "Build all stored polygon data\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBPoly\fP > \fBPolys\fP"
.br
.RI "The list of polygon data\&. "
.ti -1c
.RI "Shader \fBRoad_Shader\fP"
.br
.RI "The parking lot shader\&. "
.ti -1c
.RI "Shader \fBBuilding_Shader\fP"
.br
.RI "The building extrusion shader\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBStructure\fP class stores and builds all simulation network buildings and Points of Interest\&. 


.SH "Member Function Documentation"
.PP 
.SS "void Structure\&.Build ()"

.PP
Build all stored polygon data\&. 
.SS "void Structure\&.ClearData ()"

.PP
Clear all current simulation polygon data\&. 
.SH "Member Data Documentation"
.PP 
.SS "Shader Structure\&.Building_Shader"

.PP
The building extrusion shader\&. 
.SS "List<\fBPoly\fP> Structure\&.Polys"

.PP
The list of polygon data\&. 
.SS "Shader Structure\&.Road_Shader"

.PP
The parking lot shader\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AR Sandbox for OSU Civil Construction Engineering from the source code\&.
