.TH "Traffic_Light" 3 "Mon Jun 10 2019" "Version 2.0" "AR Sandbox for OSU Civil Construction Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Traffic_Light \- A struct representing a Sumo Network \fBTrafficLight\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< string > \fBControlledLanes\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBProgram\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBPhaseDuration\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct representing a Sumo Network \fBTrafficLight\fP\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for AR Sandbox for OSU Civil Construction Engineering from the source code\&.
