.TH "UserController" 3 "Mon Jun 10 2019" "Version 2.0" "AR Sandbox for OSU Civil Construction Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Camera \fBMain_Camera\fP"
.br
.ti -1c
.RI "GameObject \fBCanvas\fP"
.br
.ti -1c
.RI "float \fBspeed\fP = 2\&.0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AR Sandbox for OSU Civil Construction Engineering from the source code\&.
