.TH "VirtualButtonAction" 3 "Mon Jun 10 2019" "Version 2.0" "AR Sandbox for OSU Civil Construction Engineering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VirtualButtonAction \- Provides a simple, abstract interface for virtual buttons that can be used from the Unity editor\&. This script must be attached to a Virtual Button\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IVirtualButtonEventHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnButtonPressed\fP (VirtualButtonBehaviour vb)"
.br
.ti -1c
.RI "void \fBOnButtonReleased\fP (VirtualButtonBehaviour vb)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBonButtonDown\fP"
.br
.ti -1c
.RI "UnityEvent \fBonButtonUp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides a simple, abstract interface for virtual buttons that can be used from the Unity editor\&. This script must be attached to a Virtual Button\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for AR Sandbox for OSU Civil Construction Engineering from the source code\&.
